version: '3'
services:
  postgres:
    #image: koinotice/postgres:latest
    build: "./docker/postgres"
    container_name: docker_postgres
    restart: "always"
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "pmker"
      POSTGRES_USER: "pmker"
      POSTGRES_PASSWORD: "Zheli123!!@#"
      volumes:
#        - /hash/data/postgresql:/var/lib/postgresql/data

  nats:
    image: nats-streaming:latest
    restart: always
    container_name: docker_nats
    command: -m 8222 --store SQL --sql_driver postgres --sql_source "postgres://pmker:Zheli123@postgres/pmker?sslmode=disable"
    ports:
      - "4222:4222"
      - "8222:8222"

  mongo:
    image: mongo
    restart: always
    container_name: docker_mongo
    volumes:
      - /hash/data/mongo/data:/data/db
    ports:
      - 27017:27017

  redis:
    image: redis
    restart: always
    container_name: docker_redis
    volumes:
      - ./docker/data/Shanghai:/etc/localtime
      - /hash/data/redis/data:/data
    ports:
      - 6379:6379

  gitea:
    image: "gitea/gitea:latest"

    volumes:
      - /hash/data/gitea-demo:/data  # to mount custom Caddyfile
    ports:
      - "10080:3000"
      - "10022:22"



